name: Publish docs via GitHub Pages

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: cd docs/ && pip install git+https://${GH_TOKEN}@github.com/qianmoq/mkdocs-material-insiders.git
      - run: cd docs/ && pip install -r requirements.txt
      - run: cd docs/ && mkdocs gh-deploy --force

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
